# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
variables:
  tag: $(Build.BuildId)
  name: $(Build.Buildname)

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: CmdLine@2
  inputs:
    script: |
      echo 
      echo present directory is 
      pwd
      echo and the contents are
      ls
      echo $(tag) > buildinfo.txt
      echo
      cat buildinfo.txt
      ls
